/**
 * Runtime Three.js surface used by the visual mode.
 *
 * React Three Fiber's Canvas registers every export from the bare `three`
 * module as a JSX constructor. Re-exporting the complete Three namespace keeps
 * unrelated loaders, animation, audio, and XR code in the visual-mode chunk.
 * Vite aliases only the exact bare import to this catalogue; addon imports such
 * as `three/examples/jsm/*` remain untouched.
 */
export {
  ACESFilmicToneMapping,
  AmbientLight,
  BasicShadowMap,
  BoxGeometry,
  BufferAttribute,
  BufferGeometry,
  CircleGeometry,
  Clock,
  Color,
  ColorManagement,
  ConeGeometry,
  Controls,
  CylinderGeometry,
  DirectionalLight,
  DoubleSide,
  Group,
  IcosahedronGeometry,
  InstancedBufferAttribute,
  InstancedMesh,
  Layers,
  LinearSRGBColorSpace,
  MathUtils,
  Mesh,
  MeshBasicMaterial,
  MeshStandardMaterial,
  MOUSE,
  NoToneMapping,
  NormalBlending,
  Object3D,
  OrthographicCamera,
  PCFShadowMap,
  PCFSoftShadowMap,
  PerspectiveCamera,
  Plane,
  PlaneGeometry,
  PointLight,
  Points,
  Quaternion,
  Ray,
  Raycaster,
  RGBAFormat,
  Scene,
  ShaderMaterial,
  SphereGeometry,
  Spherical,
  SRGBColorSpace,
  TOUCH,
  TorusGeometry,
  UnsignedByteType,
  Vector2,
  Vector3,
  VSMShadowMap,
  WebGLRenderer,
} from 'three/src/Three.js';
